# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
target 'TTScrollContentViewDemo' do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# Pods for TTScrollContentViewDemo
    pod 'Masonry'
    use_frameworks!
# pod 'ReactiveCocoa'
end
